image: viniciusarcanjo/phpipam-pyclient-docker:dev

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
    - lint_tests
    - integration_tests

lint_tests:
    stage: lint_tests
    script:
        # find all py files excluding hidden files
        - find . -type f | grep -v '/\.' | xargs ls | egrep ".py$" | xargs pylama

.integration_tests: &integration_def
  stage: integration_tests
  after_script:
    - docker ps
    - sleep 10
    - docker ps
    - docker exec phpipampyclient_phpipam_pyclient_1 /bin/bash -c 'python3 -m pytest tests/test_phpipam_installation.py -v'
    - docker exec phpipampyclient_phpipam_pyclient_1 /bin/bash -c 'python3 -m pytest tests/test_phpipam_client.py -v'
    - docker exec phpipampyclient_phpipam_pyclient_1 /bin/bash -c 'tox'

test_phpipam_1.3.1:
    <<: *integration_def
    script:
    - docker-compose -p phpipampyclient up -d

test_phpipam_1.3:
    <<: *integration_def
    script:
    - docker-compose -p phpipampyclient -f docker-compose-1.3.yml up -d
